<?php

namespace App\Enums\Email;

enum EmailTypeEnum:string
{
    // User Authentication Related
    case ACCOUNT_VERIFICATION='ACCOUNT_VERIFICATION_EMAIL';
    case PASSWORD_RESET='PASSWORD_RESET_EMAIL';
    case EMAIL_VERIFICATION_REQUEST='EMAIL_VERIFICATION_REQUEST';
    case ACCOUNT_SUSPENSION='ACCOUNT_SUSPENSION_EMAIL';
    // Event Registeration/Booking
    case REGISTRATION_CONFIRMATION='REGISTRATION_CONFIRMATION_EMAIL';
    case TICKET_PURCHASE_RECEIPTS='TICKET_PURCHASE_RECEIPTS_EMAIL';
    case REGISTRATION_UPDATE='REGISTRATION_UPDATE_EMAIL';
    case WAITLIST_NOTIFICATION='WAITLIST_NOTIFICATION_EMAIL';
    // Event Communication
    case EVENT_INVITATION='EVENT_INVITATION_EMAIL';
    case EVENT_REMINDER='EVENT_REMINDER_EMAIL';
    case EVENT_SCHEDULE_UPDATES='EVENT_SCHEDULE_UPDATES_EMAIL';
    case LOCATION_CHANGES='LOCATION_CHANGES_EMAIL';
    case EVENT_CANCELLATION_NOTIFICATION='EVENT_CANCELLATION_NOTIFICATION_EMAIL';
    case FOLLOW_UPS='FOLLOW_UPS_EMAIL';
    case FEEDBACK_REQUEST='FEEDBACK_REQUEST_EMAIL';
    // Payment Related
    case PAYMENT_CONFIRMATION='PAYMENT_CONFIRMATION_EMAIL';
    case PAYMENT_FAILED_NOTIFICATION='PAYMENT_FAILED_NOTIFICATION_EMAIL';
    case REFUND_NOTIFICATION='REFUND_NOTIFICATION_EMAIL';
    case INVOICE_EMAIL='INVOICE_EMAIL';
}